# Generated by Django 3.2.5 on 2023-01-09 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='name',
            field=models.ForeignKey(db_column='filename', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.board'),
        ),
    ]
