# Generated by Django 3.2.5 on 2023-01-09 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230109_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='filename',
            field=models.ForeignKey(db_column='filename', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='main.board'),
        ),
    ]
